;------------------------------------------------------------------------------
; 3rd Person Pronouns
;------------------------------------------------------------------------------
;Forces you to refer to yourself as whatever your Custom Pronoun is set to (ie. "I" => "Doll", "My" => "Toys's"...)

if (3rdPronouns = 1){
	Hotstring("B Z0")
	Hotstring("::do i", "does " . Pronoun)
	Hotstring("::am i", "is " . Pronoun)
	Hotstring("::have i", "has " . Pronoun)
	Hotstring("::i", Pronoun)
	Hotstring("::me", Pronoun)
	Hotstring("::my", Pronoun . "'s")
	Hotstring("::mine", Pronoun . "'s")
	Hotstring("::myself", Pronoun . "self")
	Hotstring(":: am", " is")
	Hotstring("::i'm", Pronoun . " is")
	Hotstring("::im", Pronoun . " is")
	Hotstring(":: have", " has")
	Hotstring("::i've", Pronoun . " has")
	Hotstring("::ive", Pronoun . " has")
	Hotstring("::i'll", Pronoun . " will")
	Hotstring("::i'd", Pronoun . " would")
	;3rd Person Verbs
	Hotstring(":: feel", " feels")
	Hotstring(":: fuck", " fucks")
	Hotstring(":: bend", " kneels")
	Hotstring(":: like", " likes")
	Hotstring(":: bounce", " bounces")
	Hotstring(":: love", " loves")
	Hotstring(":: obey", " obeys")
	Hotstring(":: please", " pleases")
	Hotstring(":: suck", " sucks")
	Hotstring(":: want", " wants")
	Hotstring(":: wish", " wishes")
	Hotstring(":: melt", " melts")
	Hotstring(":: drop", " drops")
	Hotstring(":: sink", " sinks")
	Hotstring(":: masturbate", " masturbates")
	Hotstring(":: jerk", " jerks")
	; Common Action Verbs
	Hotstring(":: act", " acts")
	Hotstring(":: agree", " agrees")
	Hotstring(":: arrive", " arrives")
	Hotstring(":: ask", " asks")
	Hotstring(":: bring", " brings")
	Hotstring(":: build", " builds")
	Hotstring(":: buy", " buys")
	Hotstring(":: call", " calls")
	Hotstring(":: climb", " climbs")
	Hotstring(":: close", " closes")
	Hotstring(":: come", " comes")
	Hotstring(":: cry", " cries")
	Hotstring(":: dance", " dances")
	Hotstring(":: dream", " dreams")
	Hotstring(":: drink", " drinks")
	Hotstring(":: eat", " eats")
	Hotstring(":: enter", " enters")
	Hotstring(":: exit", " exits")
	Hotstring(":: fall", " falls")
	Hotstring(":: fix", " fixes")
	Hotstring(":: guess", " guesses")
	Hotstring(":: give", " gives")
	Hotstring(":: go", " goes")
	Hotstring(":: grab", " grabs")
	Hotstring(":: help", " helps")
	Hotstring(":: hit", " hits")
	Hotstring(":: hop", " hops")
	Hotstring(":: joke", " jokes")
	Hotstring(":: jump", " jumps")
	Hotstring(":: kick", " kicks")
	Hotstring(":: know", " knows")
	Hotstring(":: leave", " leaves")
	Hotstring(":: lift", " lifts")
	Hotstring(":: listen", " listens")
	Hotstring(":: make", " makes")
	Hotstring(":: march", " marches")
	Hotstring(":: mean", " means")
	Hotstring(":: move", " moves")
	Hotstring(":: need", " needs")
	Hotstring(":: nod", " nods")
	Hotstring(":: open", " opens")
	Hotstring(":: play", " plays")
	Hotstring(":: push", " pushes")
	Hotstring(":: read", " reads")
	Hotstring(":: ride", " rides")
	Hotstring(":: run", " runs")
	Hotstring(":: scream", " screams")
	Hotstring(":: send", " send")
	Hotstring(":: shout", " shouts")
	Hotstring(":: sing", " sings")
	Hotstring(":: sit", " sits")
	Hotstring(":: smile", " smiles")
	Hotstring(":: spend", " spends")
	Hotstring(":: stand", " stands")
	Hotstring(":: talk", " talks")
	Hotstring(":: throw", " throws")
	Hotstring(":: touch", " touches")
	Hotstring(":: send", " send")
	Hotstring(":: turn", " turns")
	Hotstring(":: vist", " visits")
	Hotstring(":: vote", " votes")
	Hotstring(":: wait", " waits")
	Hotstring(":: walk", " walks")
	Hotstring(":: write", " writes")
	Hotstring(":: yell", " yells")
	;Other Verbs
	Hotstring(":: accept", " accepts")
	Hotstring(":: ache", " aches")
	Hotstring(":: achieve", " achieves")
	Hotstring(":: acquire", " acquires")
	Hotstring(":: add", " adds")
	Hotstring(":: adjust", " adjusts")
	Hotstring(":: admire", " admires")
	Hotstring(":: advise", " advises")
	Hotstring(":: allow", " allows")
	Hotstring(":: announce", " announces")
	Hotstring(":: answer", " answers")
	Hotstring(":: apologise", " apologises")
	Hotstring(":: applaud", " applauds")
	Hotstring(":: approach", " approaches")
	Hotstring(":: approve", " approves")
	Hotstring(":: argue", " argues")
	Hotstring(":: arise", " arises")
	Hotstring(":: arrange", " arranges")
	Hotstring(":: attract", " attracts")
	Hotstring(":: avoid", " avoids")
	Hotstring(":: awake", " awakes")
	Hotstring(":: banish", " banishes")
	Hotstring(":: beg", " begs")
	Hotstring(":: begin", " begins")
	Hotstring(":: behave", " behaves")
	Hotstring(":: believe", " believes")
	Hotstring(":: belong", " belongs")
	Hotstring(":: bet", " bets")
	Hotstring(":: bite", " bites")
	Hotstring(":: blow", " blows")
	Hotstring(":: blush", " blushes")
	Hotstring(":: break", " breaks")
	Hotstring(":: breed", " breeds")
	Hotstring(":: caress", " caresses")
	Hotstring(":: carry", " carries")
	Hotstring(":: hope", " hopes")
	Hotstring(":: see", " sees")
	Hotstring(":: meet", " meets")
	Hotstring(":: thank", " thanks")
	Hotstring(":: type", " types")
	Hotstring(":: use", " uses")
	Hotstring("reset")
}


